includes: error: check if SUCCESS defined
These macros are defined in aducm drivers so this change eliminates
the redefinition of SUCCESS and FAILURE warning.

Signed-off-by: Mihail Chindris <mihail.chindris@analog.com>