jesd204_core: Remove unused printf argument
Fixes the following warnings:
../src/jesd_core.c:268:14: warning: too many arguments for format [-Wformat-extra-args]
    ad_printf("SYSREF alignment ERROR\n",

Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>