tools: scripts: Add dependency on make_dirs
The correct sequence in the build process is to first create the
directory structure for all the source files (in build/app), and then
create the symlinks for those files.

Since 54c826c1 ("fix incremental build from Git Bash"), the directory
and symlink creation have been moved to different make rules, however
there is no dependency between them. This results in compilation errors
whenever a multithreaded build is done:

[16:08:56] Building for maxim
[16:08:56] Building for target max32690
[16:08:56] Creating IDE project
ln: failed to create symbolic link 'Downloads/no-OS/projects/apard32690/build/app/noos/drivers/api/no_os_dma.c': No such file or directory
make[1]: *** [../../tools/scripts/generic.mk:391: Downloads/no-OS/projects/apard32690/build/app/noos/drivers/api/no_os_dma.c] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [../../tools/scripts/generic.mk:267: all] Error 2

Fix the issue by adding the dependency on make_dirs.

Fixes: 54c826c1 ("fix incremental build from Git Bash")
Signed-off-by: Ciprian Regus <ciprian.regus@analog.com>